# Generated by Django 5.1.2 on 2024-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_used_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
