# Generated by Django 5.1.2 on 2024-10-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_shipped_date_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('arrive', 'Arrived')], default='ordered', max_length=20),
        ),
    ]
